### ISSUE TITLE
Contenido para sección de Servicios

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/civica.digital#57]
Grupos: 

**Aplicaciones Cívicas**
En móviles, web u otros dispositivos, creamos tecnología cívica con aliados para resolver problemas y fortalecer procesos ciudadanos. 

**Datos Abiertos**
Abrimos organizaciones y gobiernos para hacerlos transparentes y fomentar la colaboración e innovación en sus objetivos.

**Capacitaciones**
Desde apertura hasta procesos para desarrollar, capacitamos equipos en las nuevas formas formentar ciudadanía con tecnología.

**Comment by paulinabustos** [comment]
¿cómo ven @juanpabloe @sandychocochips ?

**Comment by sandychocochips** [comment]
me gusta! @paulinabustos

**Comment by juanpabloe** [comment]
:+1:
